# Generated by Django 4.0.4 on 2022-05-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_image_job_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(blank=True, height_field=80, null=True, upload_to='jobs', width_field=80),
        ),
    ]
