# Generated by Django 4.0.4 on 2022-05-16 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='appliedjob',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.job'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apply',
            name='coverletter',
            field=models.TextField(),
        ),
    ]
