# Generated by Django 4.0.4 on 2022-05-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_apply_appliedjob_alter_apply_coverletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='coverletter',
            field=models.TextField(max_length=500),
        ),
    ]
